server:
  port: 9002
spring:
  application:
    name: microservice-movie
eureka:
  client:
    register-with-eureka: true #作为客户端要注册到Eureka
    fetch-registry: true #作为客户端需要从Eureka获取注册信息
    service-url: #客户端注册地址
      defaultZone: http://127.0.0.1:8888/eureka
      #修改提供方获取注册信息的间隔时间
    registry-fetch-interval-seconds: 5
  instance:
    #优先使用该服务的IP地址注册到Eureka，在生产环境建议为true
    prefer-ip-address: true
microservice-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启Hystrix
feign:
  hystrix:
    enabled: true
