server:
  port: 9101
spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    jpa:
      show-sql: true
      generate-ddl: true #是否自动建表
      database: mysql #jpa连接数据库类型
eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url:  # 客户端注册地址
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
    prefer-ip-address: true
    # 修改续约间隔时间
    lease-renewal-interval-in-seconds: 5
    # 修改服务失效时间
    lease-expiration-duration-in-seconds: 10
